const spg = [
"Sjoveste grin",
"Bedste musiksmag"
,"Bedste tøjstil"
,"Drikker mest"
,"Blir hurtigst fuld"
,"Svigermors drøm"
,"Har haft et crush på en lærer"
,"Scorer mest"
,"Scorer bedst"
,"Bedst i skolen"
,"Tisser mest i badet"
,"Ville være med i paradise" 
,"Har haft et crush på en i selskabet"
,"Tuder mest til film"
,"Mislykkes med at score" 
,"Er mest på tinder"
,"Har haft sex i en pool"
,"Får først børn"
,"Har en STD"
,"Er mest liderlig"
,"Scorer i dag"
,"Er bedst til at ride"
,"Prøver hårdest"
,"Bedst i sengen"
,"Pæneste frisyre"
,"Har haft sex med flest"
,"Gifter sig til penge"
,"På kontanthjælp"
,"Bruger flest penge"
,"I fængsel om 5 å"
,"Mest kreativ"
,"Tænder på 10 år+"
,"Hvem er i bedst form"
,"Har sex med en de mødte samme dag"
,"Varmest på floor"
,"Mest gavmild"
,"Blir først gift"
,"Er mest moden"
,"Hvem har jeg haft et crush på"
,"bedst til at tegne"
,"Værste musiksmag"
,"Blackouter"
,"Hader børn"
,"Bruger flest penge i lidl"
,"Får højeste uddannelse"
,"Mest kinky aka freaky"
,"Bedste røv"
,"Tager sig selv mest seriøs"
,"Ku mest thomas (cobs far)"
,"Hvem har færrest penge"
,"hvem får ingen uddannelse"
,"Brænder flest penge af i byen"
,"Hvem spiser mest usundt"
,"Hvem sender flest nudes"
,"Største fedterøv"
,"Først dement"
,"Bliver rigest"
,"Mest klodset"
,"Mest big dick energy"
,"Tager først hjem"
,"Sover mest"
,"Snorker mest"
,"Ku mest rødhårede"
,"Blir først skilt"
,"Har mommyissues"
,"Flirter med tjenere"
,"Vil gøre mest for penge"
,"Kan drikke flest øl"
,"Kysser bedst"
,"Skriver mest disc i chess"
,"Sadist i sengen"
,"Ku joine en kult"
,"tror på compatibility i stjernetegn"
,"Har den lækreste søskende"
,"Ville være into foodsex"
,"Sælger feetpics"
,"Køber feetpics"
,"Har skægfetish"
,"Har sværest ved at gro skæg"
,"Flotteste bryster"
,"Største simp"
,"Mister sin mødom sidst"
,"Mest tilbøjelig til at sniffe lim"
,"Får aldrig et nytårskys"
,"Ku få trampstamp i en brændert"
,"Har en piercing i en kønsdel"
,"Ødelægger sit hår efter breakup"
,"Mest desperat"
,"Onanerer mest"
,"Er mest til arierer"
,"Dyrest som prostitueret"
,"Har mest behårede fødder"
,"Ku få en fremtid i pornoindustrien"
,"Størst sandsynlighed for at falde for internetscam"
,"Ville få plastikoperation"
,"Ville forelske sig i et one night stand"
,"Kan til tider ligne en blotter"
,"Hvem er mest basic"
,"Har de flotteste læber"
,"Ku barbere sig skaldet"
,"Gir bedste blowjob"
,"Ser mest porno"
,"Betaler for onlyfans"
,"Er på onlyfans"
,"Afhængig af sex"
,"Få den op i røven"
,"Mest brug for et safe space"
,"Blir mest krænket"
,"Mest romantisk"
,"spilder mest øl" 
,"Brækker sig mest"
,"Har haft sex det mærkeligste sted"
,"Går mest komando"
,"Går mindst i bad"
,"Mest selvtillid"
,"Burde have mere selvtillid"
,"Roder mest"
,"Går i samme undertøj 3 dage i streg"
,"Er mest nærig"
,"Mest toxic"
,"ælder hurtigst"
,"Værst på første dates"
,"Scorer på floor konstant"
,"Griner af små børn der kommer til skade"
,"Ville få en tatoveringen I <33 mom"
,"Hvem har den flotteste bror/søster"
,"Hvem ville have sex for at scorer sig et job"
]